/**
 * Example of creating a custom AI provider
 */

import {
  AIProvider,
  ProviderRegistry,
  FileNamingSDK,
} from '../src';
import {
  ProviderCapabilities,
  ProviderRequestContext,
  ProviderResponse,
} from '../src/types/provider';
import { BaseProviderConfig } from '../src/types/config';

/**
 * Example: Custom Provider implementation
 * This demonstrates how easy it is to add a new AI provider
 */
class CustomAIProvider extends AIProvider {
  readonly name = 'custom';

  readonly capabilities: ProviderCapabilities = {
    supportsVision: false,
    supportsStreaming: false,
    supportsBatch: false,
    supportsCustomModels: true,
    maxTokens: 2048,
  };

  protected initializeClient(): unknown {
    // Initialize your custom AI client here
    return {
      // Your custom client implementation
      generate: async (prompt: string) => {
        // Example: Call to your custom API
        return {
          text: `custom_generated_name_for_${Date.now()}`,
        };
      },
    };
  }

  protected async executeRequest(
    context: ProviderRequestContext,
  ): Promise<ProviderResponse> {
    try {
      // Call your custom AI API
      const response = await (this.client as any).generate(context.userPrompt);

      // Format the response
      return {
        originalName: context.request.context.originalName,
        suggestedName: this.sanitizeResponse(response.text),
        confidence: 0.9,
        reasoning: 'Generated by custom AI provider',
      };
    } catch (error) {
      throw new Error(`Custom provider error: ${error instanceof Error ? error.message : 'Unknown'}`);
    }
  }

  protected async performConnectionTest(): Promise<boolean> {
    try {
      // Test your custom API connection
      return true;
    } catch {
      return false;
    }
  }

  protected requiresApiKey(): boolean {
    return true; // Set to false if your provider doesn't need an API key
  }

  protected isValidModel(model: string): boolean {
    // Validate your custom models
    return model.length > 0;
  }
}

/**
 * Usage example
 */
async function main() {
  console.log('🔧 Custom Provider Example\n');

  // Step 1: Register your custom provider
  console.log('1. Registering custom provider...');
  ProviderRegistry.register('custom', CustomAIProvider, {
    description: 'My custom AI provider',
    version: '1.0.0',
  });

  console.log('   ✅ Registered!');
  console.log('   Available providers:', ProviderRegistry.getAvailable());

  // Step 2: Use your custom provider
  console.log('\n2. Using custom provider...\n');

  const sdk = new FileNamingSDK({
    provider: {
      type: 'custom',
      apiKey: 'your-custom-api-key',
      model: 'your-custom-model',
      maxRetries: 3,
      timeout: 30000,
      temperature: 0.7,
    } as BaseProviderConfig,
  });

  // Test the custom provider
  try {
    const testFile = '/Users/jinhu/Projects/AIO/AIO 注册材料/AIO Manufacturing Solution LLC LOA.pdf';
    const result = await sdk.nameFile(testFile, {
      prompt: 'Generate a descriptive filename',
    });

    console.log('   Result:');
    console.log(`     Original: ${result.originalName}`);
    console.log(`     Suggested: ${result.suggestedName}`);
    console.log(`     Confidence: ${(result.confidence * 100).toFixed(0)}%`);
  } catch (error: any) {
    console.log(`   Error: ${error.message}`);
  }

  console.log('\n✨ Custom provider example complete!\n');
  console.log('💡 Tip: You can create providers for any AI service:');
  console.log('   - LM Studio');
  console.log('   - Hugging Face Inference API');
  console.log('   - Azure OpenAI');
  console.log('   - Custom trained models');
  console.log('   - Any other AI service\n');
}

main().catch(console.error);